version: "3"

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 123
    volumes:
      - mariadb_data:/var/lib/mysql
  wordpress:
    depends_on:
      - mariadb
    image: wordpress:fpm-alpine
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - wp_data:/var/www/html
volumes:
  mariadb_data: {}
  wp_data: {}
